[project]
name = "agent-evaluating"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "s.touqeer@pharmatrace.io", email = "s.touqeer@pharmatrace.io" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
agent-evaluating = "agent_evaluating:main"

[build-system]
requires = ["uv_build>=0.12.21,<0.13.0"]
build-backend = "uv_build"
